import { collection, getDocs } from "firebase/firestore";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { PostProps } from "../components/PostCard";
import PostGrid from "../components/PostGrid";
import { firestoreDb } from "../firebase/clientApp";
import styles from "../styles/Home.module.scss";

const Home: NextPage<{ posts: PostProps[] }> = ({ posts }) => {
  console.log(posts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostGrid posts={posts} />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const querySnapshot = await getDocs(collection(firestoreDb, "posts"));

  const posts = querySnapshot.docs.map((doc) => doc.data());
  return {
    props: { posts },
  };
};

export default Home;
