import { Box } from "@chakra-ui/react";
import { collection, getDocs, orderBy, query } from "firebase/firestore";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import PostGrid from "../components/PostGrid";
import { firestoreDb } from "../firebase/clientApp";
import styles from "../styles/Home.module.scss";
import { Post } from "../types/Post";

const Home: NextPage<{ posts: Post[] }> = ({ posts }) => {
  console.log(posts);
  return (
    <Box className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostGrid posts={posts} />
    </Box>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const q = query(collection(firestoreDb, "posts"), orderBy("timestamp", "desc"));
  const querySnapshot = await getDocs(q);

  const posts = querySnapshot.docs.map((doc) => doc.data());
  return {
    props: { posts },
  };
};

export default Home;
